# COMPOSE_CONVERT_WINDOWS_PATHS=1
#
# @link https://www.ruanyifeng.com/blog/2016/07/yaml.html
#

version: "3.8"

x-common:
  &common
  # fix me
  working_dir: /app
  restart: "no"

services:
  workspace:
    &workspace
    image: khs1994/php:${LNMP_PHP_VERSION:-8.0.6}-composer-alpine
    networks:
      - backend
    volumes:
      - vscode-server:/root/.vscode-server
      - vscode-server-insiders:/root/.vscode-server-insiders
      - vscode-phpls-cache:/root/.phpls
      # fix me
      # linux/macOS
      # - ./app:/app
      # fix me 将依赖挂载到数据卷
      # - vendor:/app/demo/vendor
      - ${APP_ROOT}:/app

      # composer
      - type: volume
        source: composer-cache-data
        target: /tmp/composer/cache
      - type: bind
        source: ./.devcontainer/composer.config.json
        target: /tmp/composer/config.json
      # - type: bind
      #   source: ./.devcontainer/composer.auth.json
      #   target: /tmp/composer/auth.json

      # php
      - type: bind
        source: ./.devcontainer/docker-php.ini
        target: /usr/local/etc/php/conf.d/docker-php.ini
      - ./.devcontainer/php-log:/var/log/php

      # node
      # 如果你修改了 .npmrc 中的路径，请同步更改这里的数据卷映射关系
      - type: bind
        source: ./.devcontainer/.npmrc
        target: /usr/local/etc/npmrc
      - npm-global-data:/tmp/node/npm
      - npm-cache-data:/tmp/node/.npm
    # 如果在 PhpStorm 中使用，无需开放端口，必须注释掉 `ports` 项
    # vsCode 运行在容器中，故必须开放 9003 供 xdebug 连接
    ports:
      # xdebug port
      - 9003:9003
    restart: always
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      APP_ENV: development
      TZ: Asia/Shanghai

  composer:
    << : *workspace
    << : *common
    image: "khs1994/php:${LNMP_PHP_VERSION:-8.0.6}-composer-alpine"
    command: [] # install | update

  npm:
    << : *workspace
    << : *common
    image: node:${LNMP_NODE_VERSION:-16.2.0}-alpine
    entrypoint: npm
    command: [] # install | ["run","dev"] |

networks:
  backend:

volumes:
  composer-cache-data:
  vscode-server:
  vscode-server-insiders:
  vscode-phpls-cache:
  vendor:
    # 或者复用其他数据卷
    # external: true
    # name: lnmp_laravel_vendor
  npm-global-data:
  npm-cache-data:
