version: "3.8"

#
# @link https://www.ruanyifeng.com/blog/2016/07/yaml.html
#

x-common:
  &common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

#
# 这里的文件具有最高优先级，可以通过以下命令查看最终的 compose 文件
#
# $ ./lnmp-docker config > docker-compose.yaml
#
# # 自定义镜像
# $ ./lnmp-docker build-config > docker-compose.build.yaml
#

services:
  ## https://docs.docker.com/compose/extends/

  # add service
  my-service:
    image: ${LNMP_LIBRARY_NS:-library}/bash

  # override service

  # php8:
  #   &php8
  #   # ! change php8 default image
  #   image: username/php:${LNMP_PHP8_VERSION:-8.0.6}-fpm-alpine
  #   # ! cn mirror image
  #   # image: ccr.ccs.tencentyun.com/khs1994/php:${LNMP_PHP8_VERSION:-8.0.6}-fpm-alpine
  #   # ! s6
  #   # image: khs1994/php:${LNMP_PHP8_VERSION:-8.0.6}-s6-alpine
  #   # command: []
  #   # volumes:
  #   #   - ./config/s6/services.d:/etc/services.d
  #   # ! open more port
  #   ports:
  #     - "9000"
  #     - "10001:10001"
  #   # ! add more volumes
  #   volumes:
  #     - git-sync-data:/app/git-sync

  # composer:
  #   << : *php8
  #   volumes:
  #     - ./config/composer/auth.json:/tmp/composer/auth.json:cached

  # nginx-unit:
  #   << : *php8

  # mysql:
  #   # change default volumes settings
  #   volumes:
  #     - ./data:/var/lib/mysql

# More Demo

  # phpmyadmin:
  #   image: phpmyadmin:5.1.0-fpm-alpine
  #   volumes:
  #     - phpmyadmin:/var/www/html
  #   healthcheck:
  #     test: ["NONE"]

  nginx:
    # volumes:
    # - git-sync-data:/app/git-sync
    # - phpmyadmin:/var/www/html
    depends_on:
      - php8

  swoole:
    << : *common
    image: khs1994/php:${LNMP_PHP_VERSION:-8.0.6}-swoole-alpine
    # command 指令只需传入文件名即可
    command:
      - /app/swoole/index.php
    ports:
      - 10001:10001
    networks:
      - backend
    volumes:
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}:cached
      - ./config/php/${LNMP_PHP_INI:-php.development.ini}:/usr/local/etc/php/php.ini:ro,cached
      - ./config/php/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini:ro,cached
      - ./log/php:/var/log/php:cached

# volumes:
  # git-sync-data:
  # phpmyadmin:
