name: containerd
version: 1.5.2
pre-version: 1.5.2
url: "https://github.com/containerd/containerd/releases/download/v${VERSION}/containerd-${VERSION}-${env:lwpm_os}-amd64.tar.gz"
url-mirror: https://download.fastgit.org/containerd/containerd/releases/download/v${VERSION}/containerd-${VERSION}-${env:lwpm_os}-amd64.tar.gz
scripts:
  platform-reqs: if($IsMacOs){echo $False}
  dist: |
    _mkdir $env:LWPM_PKG_ROOT/dist

    curl -L `
      $url `
      -o $env:LWPM_PKG_ROOT/dist/$filename
platform:
  - architecture: amd64
    os: linux
  - architecture: amd64
    os: windows
hash-url:
  sha256: https://github.com/containerd/containerd/releases/download/v${VERSION}/containerd-${VERSION}-${env:lwpm_os}-amd64.tar.gz.sha256sum
