version: "3.8"

x-common:
  &common
  restart: always
  env_file: ./cli/timezone.env
  networks:
    - backend
  # dns:
  #   - ${DNS:-114.114.114.114}

x-common-label:
  &common-label
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  rabbitmq:
    << : *common
    image: ${LNMP_BUILD_DOCKER_IMAGE_PREFIX:-khs1994}/rabbitmq:${LNMP_RABBITMQ_VERSION:-3.8.16}-management-alpine
    volumes:
      - type: volume
        source: rabbitmq-data
        target: /var/lib/rabbitmq
    ports:
      - "${LNMP_RABBITMQ_PORT_1000:-127.0.0.1:15672}:15672"
      - "${LNMP_RABBITMQ_PORT:-127.0.0.1:5672}:5672"

volumes:
  rabbitmq-data:
    << : *common-label
