version: "3.8"

x-common:
  &common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  httpd:
    << : *common
    image: ${LNMP_LIBRARY_NS:-library}/httpd:${LNMP_HTTPD_VERSION:-2.4.48}-alpine
