version: "3.8"

x-common:
  &common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  example:
    << : *common
    image: example:${LNMP_EXAMPLE_VERSION:-x.y.z}-alpine
    # image: ${LNMP_LIBRARY_NS:-library}/example:${LNMP_EXAMPLE_VERSION:-x.y.z}-alpine
