version: "3.8"

x-common:
  &common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:
  mongodb:
    << : *common
    image: ${LNMP_LIBRARY_NS:-library}/mongo:${LNMP_MONGODB_VERSION:-4.4.5}
