on:
  push:
    tags:
    - v20.10.*

name: Release

jobs:
  release:
    strategy:
      fail-fast: false
      # max-parallel: 1
      matrix:
        include:
          - JOB_NAME: wsl-php-builder-73
            DIST_FILE: khs1994-wsl-php73_7.3.28-debian-buster_amd64.deb
          - JOB_NAME: wsl-php-builder-74
            DIST_FILE: khs1994-wsl-php74_7.4.19-debian-buster_amd64.deb
          - JOB_NAME: wsl-php-builder-80
            DIST_FILE: khs1994-wsl-php80_8.0.6-debian-buster_amd64.deb
          - JOB_NAME: wsl-php-builder-nightly
            DIST_FILE: khs1994-wsl-php81_0.0.0-debian-buster_amd64.deb
          - JOB_NAME: wsl-php-builder-debian11-80
            DIST_FILE: khs1994-wsl-php80_8.0.6-debian-bullseye_amd64.deb
          - JOB_NAME: wsl-php-builder-ubuntu1804-73
            DIST_FILE: khs1994-wsl-php73_7.3.28-ubuntu-bionic_amd64.deb
          - JOB_NAME: wsl-php-builder-ubuntu1804-74
            DIST_FILE: khs1994-wsl-php74_7.4.19-ubuntu-bionic_amd64.deb
          - JOB_NAME: wsl-php-builder-ubuntu1804-80
            DIST_FILE: khs1994-wsl-php80_8.0.6-ubuntu-bionic_amd64.deb
          - JOB_NAME: wsl-php-builder-ubuntu2004-74
            DIST_FILE: khs1994-wsl-php74_7.4.19-ubuntu-focal_amd64.deb
          - JOB_NAME: wsl-php-builder-ubuntu2104-80
            DIST_FILE: khs1994-wsl-php80_8.0.6-ubuntu-hirsute_amd64.deb
          - JOB_NAME: wsl-php-builder-ubuntu2004-nightly
            DIST_FILE: khs1994-wsl-php81_0.0.0-ubuntu-focal_amd64.deb
          - JOB_NAME: wsl-php-builder-rhel7-73
            DIST_FILE: khs1994-wsl-php73-7.3.28-1.el7.centos.x86_64.rpm
          - JOB_NAME: wsl-php-builder-rhel8-73
            DIST_FILE: khs1994-wsl-php73-7.3.28-1.el8.centos.x86_64.rpm
          - JOB_NAME: wsl-php-builder-rhel8-74
            DIST_FILE: khs1994-wsl-php74-7.4.19-1.el8.centos.x86_64.rpm
          - JOB_NAME: wsl-php-builder-rhel8-80
            DIST_FILE: khs1994-wsl-php80-8.0.6-1.el8.centos.x86_64.rpm
          - JOB_NAME: wsl-php-builder-fc34-73
            DIST_FILE: khs1994-wsl-php73-7.3.28-1.fc34.x86_64.rpm
          - JOB_NAME: wsl-php-builder-fc34-74
            DIST_FILE: khs1994-wsl-php74-7.4.19-1.fc34.x86_64.rpm
          - JOB_NAME: wsl-php-builder-fc34-80
            DIST_FILE: khs1994-wsl-php80-8.0.6-1.fc34.x86_64.rpm
          - JOB_NAME: wsl-php-builder-fc34-nightly
            DIST_FILE: khs1994-wsl-php81-0.0.0-1.fc34.x86_64.rpm
          - JOB_NAME: wsl-php-builder-fc35-80
            DIST_FILE: khs1994-wsl-php80-8.0.6-1.fc35.x86_64.rpm
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1
    # - shell: pwsh
    #   env:
    #     NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
    #   run: |
    #     Publish-Script -Path ${PWD}/lnmp-docker.ps1 -NuGetApiKey $env:NUGET_API_KEY -Force
    - name: Create release
      run: |
        if [ "$JOB_NAME" != 'wsl-php-builder-73' ];then
          exit 0
        fi

        export GITHUB_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3)
        gh release create $GITHUB_TAG -F CHANGELOG.md --target 20.10 -t $GITHUB_TAG || true

        # deb
        sh cli/build.sh deb ${GITHUB_TAG}
        export VERSION=$( echo ${GITHUB_TAG} | cut -d "v" -f 2 )
        export DEB_NAME=khs1994-docker-lnmp_${VERSION}_amd64.deb
        ls -la cli
        sudo dpkg -i cli/${DEB_NAME}
        gh release upload ${GITHUB_TAG} cli/${DEB_NAME} --repo khs1994-docker/lnmp --clobber

        # rpm
        test $( echo "${GITHUB_TAG}" | grep alpha ) && exit 0 || true
        test $( echo "${GITHUB_TAG}" | grep beta ) && exit 0 || true
        test $( echo "${GITHUB_TAG}" | grep rc ) && exit 0 || true
        sudo apt install -y rpm
        sh cli/build.sh rpm ${GITHUB_TAG}
        export VERSION=$( echo ${GITHUB_TAG} | cut -d "v" -f 2 )
        export RPM_NAME=$( cd $HOME; ls *.rpm )
        ls -la ~/*.rpm
        gh release upload ${GITHUB_TAG} ${HOME}/${RPM_NAME} --repo khs1994-docker/lnmp --clobber

      env:
        GITHUB_REF: ${{ github.ref }}
        JOB_NAME: ${{ matrix.JOB_NAME }}
    - uses: azure/docker-login@v1
      with:
        # login-server: contoso.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        ./lnmp-docker compose --official -f
        cd wsl
        docker-compose build ${JOB_NAME}
        docker-compose push ${JOB_NAME}
        docker-compose run ${JOB_NAME} command || true
        . .env
        docker cp $( docker container ls -a --format {{.ID}} ):/${DIST_FILE} .
        export GITHUB_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3)
        gh release upload ${GITHUB_TAG} "${DIST_FILE}" --repo khs1994-docker/lnmp --clobber
      env:
        JOB_NAME: ${{ matrix.JOB_NAME }}
        GITHUB_REF: ${{ github.ref }}
        DIST_FILE: ${{ matrix.DIST_FILE }}
      name: Build
